version: "3.8"

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379

    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

    command: --save 60 1 --loglevel warning
    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s

volumes:
  redis:
    driver: local
